learning:
  sae:
    lr: 0.001
    epochs: 20
    val_freq: 3
    batch_size: 512
    batch_size_val: 128
  ama:
    lr: 0.001
    epochs: 700
    val_freq: 50
    batch_size: 64
    batch_size_val: 64
model:
  sae:
    selected_feat: ['feat_pose_x', 'feat_pose_y', 'feat_pose_z', 'feat_fingers', 'feat_goal_achieved']
    num_pus: 8
    num_attentions: 3 # this actually means arity, using 3 for now
    num_predicates: 8
    hidden_att_dim: 32
    hidden_pred_dim: 32
    hidden_dec_dim: 128
  ama:
    num_message_passing: 3
    layer_size: 128
    num_layers: 3
inference:
  max_shooting_tries: 2
  max_shooting_actions: 500 