final_op: [1, 0, 0, 0, 0, 0, 0]
neupi_non_effect_predicates: ['NotEq']
config:
  - name: "neural_u_p3"
    types: ["block"]
    ent_idx: [0]
    search_region: [0, 0, 1, 1, 1, 1, 1]
    architecture:
      type: "Selective-NormNet"
      pointnet_feat_lst: [64, 128, 256]
      initializer: "xavier"
    optimizer:
      type: "AdamW"
      kwargs:
        lr: 0.001
    lr_scheduler:
      type: "StepLR"
      kwargs:
        step_size: 20
        gamma: 0.1
    quick_skip:
      10: 0.08
    batch_vect_num: 12
    ucb_kappa: 0.2
    batch_size: 128
    epochs: 20
    gumbel_temp: 0.66
    val_freq: 4
    num_iter: 5
    matrix_vec_try: 100
    search_tree_max_level: 1
    guidance_thresh: 0.1
    loss_thresh: 0.05
    skip_train: False