learning:
  sae:
    lr: 0.001
    epochs: 20
    val_freq: 3
    batch_size: 512
    batch_size_val: 128
  ama:
    lr: 0.001
    epochs: 700
    val_freq: 50
    batch_size: 1024
    batch_size_val: 128
model:
  sae:
    selected_feat: ['feat_ee_x', 'feat_ee_y', 'feat_ee_z', 'feat_ee_qx', 'feat_ee_qy', 'feat_ee_qz', 'feat_ee_qw', 'feat_x', 'feat_y', 'feat_z', 'feat_qx', 'feat_qy', 'feat_qz', 'feat_qw']
    num_pus: 8
    num_attentions: 3 # this actually means arity, using 3 for now
    num_predicates: 12
    hidden_att_dim: 64
    hidden_pred_dim: 64
    hidden_dec_dim: 256
  ama:
    num_message_passing: 3
    layer_size: 512
    num_layers: 3
inference:
  max_shooting_tries: 150
  max_shooting_actions: 3 