final_op: [0, 0, 0, 0]
neupi_non_effect_predicates: []
config:
  - name: "neural_u_p1"
    types: ["block"]
    ent_idx: [0]
    gt: [[2, 1, 0, 0]]
    architecture: 
      type: "Selective-ResNet18"
      initializer: "xavier"
    optimizer:
      type: "AdamW"
      kwargs:
        lr: 0.001
    lr_scheduler:
      type: "StepLR"
      kwargs:
        step_size: 70
        gamma: 0.1
    batch_vect_num: 1
    batch_size: 8
    epochs: 100
    gumbel_temp: 0.66
    val_freq: 10
    num_iter: 5
    matrix_vec_try: 100
    search_tree_max_level: 3
    guidance_thresh: 0.05
    loss_thresh: 0.005
    skip_train: False